In [1]:
import numpy as np
values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6] #list
x = np.array(values) # creating array from a list
x

array([7, 4, 5, 8, 9, 0, 1, 3, 2, 6])

#### Select values using index

In [2]:
x[5] # 6th element

0

In [4]:
x[-2] # second_last

2

In [5]:
x[1::2] # odd index number values

array([4, 8, 0, 3, 6])

In [6]:
x[::2] # even index number values

array([7, 5, 9, 1, 2])

In [8]:
y = [10,11,12,13,14,15]
z = np.concatenate([x,y]) # combine x and y
z

array([ 7,  4,  5,  8,  9,  0,  1,  3,  2,  6, 10, 11, 12, 13, 14, 15])

In [9]:
z[::-1] # reverse z

array([15, 14, 13, 12, 11, 10,  6,  2,  3,  1,  0,  9,  8,  5,  4,  7])