In [1]:
# create a 2D array
import numpy as np
x = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],])


In [2]:
x.shape # rows and columns

(4, 5)

#### Accessing values with index values

In [3]:
x[1,2] # like matrix

8

In [4]:
x[3,4]

20

#### Accessing entire rows

In [5]:
x[1,:] # entire second row

array([ 6,  7,  8,  9, 10])

In [6]:
x[3,:] # entire 4th row

array([16, 17, 18, 19, 20])

In [7]:
row_1_2 = x[:2,:] # first two rows
row_1_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
x[2:,:] # Third and fourth rows

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [9]:
x[[1,3],:]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [10]:
x[-1,:] #last row

array([16, 17, 18, 19, 20])

#### Accessing Columns

In [11]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
x[:,0] # first column

array([ 1,  6, 11, 16])

In [13]:
x[:,2] # Third column

array([ 3,  8, 13, 18])

In [14]:
x[:,:2] # first two columns

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [15]:
x[:,2:] #last three columns

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [16]:
x[:,[1,4]] # second and fifth columns

array([[ 2,  5],
       [ 7, 10],
       [12, 15],
       [17, 20]])

In [17]:
x[:,-2] # second last column

array([ 4,  9, 14, 19])

In [18]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

#### Selecting the following boxes from the array

<img src="Picture1.png" alt="Drawing" align="left" style="width: 300px;"/>

In [19]:
x[1:3, 1:4] # box_1

array([[ 7,  8,  9],
       [12, 13, 14]])

In [20]:
x[:3,1:3] # box_2

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [21]:
x[1:3,2:4] # box_3

array([[ 8,  9],
       [13, 14]])

In [22]:
x[1:3,3:5] # box_4

array([[ 9, 10],
       [14, 15]])